name: Build KernelSU Manager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone KernelSU
        run: git clone https://github.com/tiann/KernelSU.git

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: |
          cd KernelSU
          chmod +x gradlew
          ./gradlew :manager:assembleRelease

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: KernelSU_Manager
          path: KernelSU/manager/build/outputs/apk/release/*.apk
